### ISSUE TITLE
Error with new version of pandas

### ISSUE THREAD

**Issue by CMM02** [pmb399/REIXSAnalysis#1]
With the upgrade of pandas package to 1.5 the parameter name of `Dataframe.to_csv()` was changed from `line_terminator` to `lineterminator`. This causes an error when trying to export a csv file of an figure.

This affects the following lines:
- https://github.com/pmb399/REIXSAnalysis/blob/af661b145d049cf4ec00abc98723cdbf54a4677a/src/reixs/LoadData.py#L385
- https://github.com/pmb399/REIXSAnalysis/blob/af661b145d049cf4ec00abc98723cdbf54a4677a/src/reixs/LoadData.py#L903
- https://github.com/pmb399/REIXSAnalysis/blob/af661b145d049cf4ec00abc98723cdbf54a4677a/src/reixs/LoadData.py#L1296

**Comment by pmb399** [comment]
Fixed. Now requires pandas>1.5.0. Please upgrade or use pip install reixs==0.6.5
